function [BiasVoltageV, CurrentDensityAm2] = importIVCurve(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [BIASVOLTAGEV, CURRENTDENSITYAM2] = IMPORTFILE(FILENAME) reads data
%  from text file FILENAME for the default selection.  Returns the data
%  as column vectors.
%
%  [BIASVOLTAGEV, CURRENTDENSITYAM2] = IMPORTFILE(FILE, DATALINES) reads
%  data for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  [BiasVoltageV, CurrentDensityAm2] = importfile("C:\Users\mrvogt\Documents\Gitlab\PVMDToolbox mCode\5_ELECTRIC\IVCurveFittingTools\HZB_2T_2915\Bot\Irradiance\JV_SHJ_HZB_2T_Bot_v7_25deg_1000Wm2.dat", [7, 97]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 08/03/2021 16:47:23

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [7, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["BiasVoltageV", "CurrentDensityAm2"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
BiasVoltageV = tbl.BiasVoltageV;
CurrentDensityAm2 = tbl.CurrentDensityAm2;
end