function [skymap,sun_idx,skytype] = perez_model(sun_azi, sun_alt, DNI, DHI, ...
    tri_azi, tri_zen, tri_area, extra_sol_power)
%PEREZ_MODEL Apply the Perez model to calculate the skymap
% Calculate radiance of every sky element for given weather conditions
% using Perez model [1]. Used for triangular sky elements generated by
% icohemisphere.m
%
% The irradiances modified by the surroundings are included in the model
% only when building the skymap. The parameters needed for the Perez model 
% are computed using the measured irradiances, not the modified ones
%
% [1]: Perez, Richard, Robert Seals, and Joseph Michalsky. "All-weather
% model for sky luminance distributionpreliminary configuration and
% validation." Solar energy 50.3 (1993): 235-245.
%
% Parameters
% ----------
% sun_azi : double
%   Sun azimuth angle [deg]
% sun_alt : double
%   Sun altitude angle [deg]
% DNI : double
%   DNI, direct normal (beam) irradiance [W/m2] (beam normal plane)
% DHI : double
%   DHI diffuse horizontal irradiance [W/m2] (horizontal plane)
% DNI_mod : double
%   DNI corrected by the shading factor
% DHI_mod : double
%   DHI corrected by the SVF
% tri_azi : double
%   Triangle center azimuth vector [deg] (length = #triangle in hemisphere)
% tri_zen : double
%   Triangle center zenith vector [deg]
% tri_area : double
%   Triangle area [sr]
% extra_sol_power: double
%   Extraterrestrial solar power computed outside the function for
%   computational improvement [W/m2]
% 
% Returns
% -------
% skymap : double
%   Sky luminance in viewing direction (not on horizontal surface) at every
%   triangle center [W/m2 sr]
%
% Developed by V. Muthukumar. Commented by A. Alcaniz

sun_zen = 90-sun_alt;

%---- Determine the closest triangle to the sun
[gamma,sun_idx] = sun_triangle(sun_azi,sun_zen,tri_azi,tri_zen);

%---- Calculate epsilon and delta
[epsilon,delta] = horse(DHI,DNI,sun_zen,extra_sol_power);

%---- Look up for coefficients a,b,c,d,e in table
[a,b,c,d,e] = alphabet(epsilon,delta,sun_zen);

%---- Calculate radiance distribution from coefficients
lv = luminous(tri_zen,gamma,a,b,c,d,e);

%---- Normalize radiance distribution
skymap = normal(lv,tri_zen,tri_area,DHI);

%---- Add direct component
skymap(sun_idx) = skymap(sun_idx) + DNI/tri_area(sun_idx);

%---- Determine skytype according to Perez model
if epsilon <= 1
    skytype = 3;
elseif epsilon >= 6
    skytype = 1;
else
    skytype = 2;
end

end


function [gamma,sun_idx] = sun_triangle(sun_azi,sun_zen,tri_azi,tri_zen)
%SUN_TRIANGLE Determine which triangle center the sun is closest to and use
%spherical law of cosines to calculate angular distance of every triangle
%center to the sun posisiton
%
% Note: this does not always guarantee that the sun is inside triangle i,
% but this will usually be the case for triangles generated by
% icohemisphere which have very similar sizes.
%
% Parameters
% ----------
% sun_azi : double
%   Sun azimuth angle [deg]
% sun_zen : double
%   Sun zenith angle [deg]
% tri_azi : double
%   Triangle center azimuth vector [deg] (length = #triangle in hemisphere)
% tri_zen : double
%   Triangle center zenith vector [deg]
% 
% Returns
% -------
% gamma : double
%   Angular distance of every triangle center to the sun position
% sun_idx : double
%   Index of the triangle with closest position to sun

gamma = acosd(cosd(sun_zen)*cosd(tri_zen)+sind(sun_zen)*sind(tri_zen).*cosd(sun_azi-tri_azi));
gamma = real(gamma);
[~,sun_idx] = min(gamma);
end


function [epsilon, delta] = horse(DHI,DNI,sun_zen,extra_sol_power)
%HORSE Calculate the sky clearness and the sky brightness (eq 4 and 5 of [1])
%
% Parameters
% ----------
% DHI : double
%   DHI diffuse horizontal irradiance [W/m2](horizontal plane)
% DNI : double
%   DNI, direct normal (beam) irradiance [W/m2] (beam normal plane)
% sun_zen : double
%   Sun zenith angle [deg]
% extra_sol_power: double
%   Extraterrestrial solar power computed outside the function for
%   computational improvement [W/m2]
%
% Returns
% -------
% epsilon : double
%   Sky clearness
% delta : double
%   Sky brightness

if sun_zen>90; sun_zen = 90; end
sun_zen_rad = deg2rad(sun_zen);

% Calculate the optical air mass. Following Kasten and Young (1989) airmass
% expression. This avoids issues when sun_zen approaches 90
air_mass = 1./(cosd(sun_zen) + 0.50572*(96.07995-sun_zen).^(-1.6364));

delta = air_mass*DHI/extra_sol_power;
if delta<0.01; delta=0.01; end

kappa = 1.041;
epsilon = ((DHI + DNI)/DHI + kappa*sun_zen_rad^3) / (1+kappa*sun_zen_rad^3);

end


function [a,b,c,d,e] = alphabet(epsilon,delta,sun_zen)
%ALPHABET Calculate coefficients a,b,c,d,e from sky clearness and
%brightness using empirical relations (eqs 6, 7, 8 of [1])
% 
% Coefficient a is a function of subcoefficients a1, a2, a3 and a4, which
% are a function of epsilon. Same for b, c, d and e. The subcoefficients,
% tabulated in table 1 in [1], are loaded from a file. Here this table is
% split up into 5 parts (A, B, C, D, E).
% 
% Parameters
% ----------
% epsilon : double
%   Sky clearness
% delta : double
%   Sky brightness
% sun_zen : double
%   Sun zenith angle [deg]
% 
% Returns
% -------
% a,b,c,d,e : double
%   Coefficients for the Perez model

load('constants/perez_table.mat','A','B','C','D','E');

sun_zen_rad = deg2rad(sun_zen);

% Select appropriate table row based on sky clearness
if epsilon<1
    error('sky clearness < 1, outside range of Perez table 1.');
end
row((epsilon>=1) & (epsilon<1.065)) = 1;
row((epsilon>=1.065) & (epsilon<1.23)) = 2;
row((epsilon>=1.23) & (epsilon<1.5)) = 3;
row((epsilon>=1.5) & (epsilon<1.95)) = 4;
row((epsilon>=1.95) & (epsilon<2.8)) = 5;
row((epsilon>=2.8) & (epsilon<4.5)) = 6;
row((epsilon>=4.5) & (epsilon<6.2)) = 7;
row(epsilon>=6.2) = 8;

% Implement the erratum found in the Perez AWM model
if (epsilon>1.065) && (epsilon<2.8) && (delta<0.2); delta = 0.2; end

% Empirical relations a = f(a1,a2,a3,a4), same for b,c,d,e
a = A(row,1) + A(row,2)*sun_zen_rad + delta * (A(row,3) + A(row,4)*sun_zen_rad);
b = B(row,1) + B(row,2)*sun_zen_rad + delta * (B(row,3) + B(row,4)*sun_zen_rad);
e = E(row,1) + E(row,2)*sun_zen_rad + delta * (E(row,3) + E(row,4)*sun_zen_rad);

if row == 1
    c = exp((delta * (C(row,1) + C(row,2) * sun_zen_rad))^C(row,3)) - C(row,4);
    d = -exp(delta*(D(row,1)+D(row,2)*sun_zen_rad)) + D(row,3) + delta * D(row,4);
else
    c = C(row,1) + C(row,2)*sun_zen_rad + delta * (C(row,3) + C(row,4)*sun_zen_rad);
    d = D(row,1) + D(row,2)*sun_zen_rad + delta * (D(row,3) + D(row,4)*sun_zen_rad);
end
end


function lv = luminous(tri_zen,gamma,a,b,c,d,e)
%LUMINOUS Calculate relative luminance of sky element at zenith angle zeta
%and sun angle gamma from coefficients a,b,c,d,e using empirical relation
%given by eq.(1) in [1]. Note: tri_zen and gamma are matrices.
% 
% Parameters
% ----------
% tri_zen : double
%   Triangle center zenith vector [deg]
% gamma : double
%   Angular distance of every triangle center to the sun position
% a,b,c,d,e : double
%   Coefficients for the Perez model
% 
% Returns
% -------
% lv : double
%   Relative luminance

load('constants/weather_params.mat', 'zen_max')
tri_zen(tri_zen>zen_max) = zen_max;

lv = (1 + a*exp(b./cosd(tri_zen))) .* (1 + c*exp(d*gamma*pi/180) + e*cosd(gamma).^2);

if any(lv<0)
    disp('There are negative values in the relative luminance.')
    disp('Please inform a developer of this issue.')
end
end


function LV = normal(lv,tri_zen,tri_area,DHI)
%NORMAL Obtain the luminance of the considered sky element eq.(3) in [1]
%
% Parameters
% ----------
% lv : double
%   Relative luminance
% tri_zen : double
%   Triangle center zenith vector [deg]
% tri_area : double
%   Triangle area [sr]
% DHI : double
%   DHI diffuse horizontal irradiance [W/m2](horizontal plane)
% 
% Returns
% -------
% LV : double
%   Luminance of the considered sky element

normalization_factor = sum(sum(lv.*tri_area.*cosd(tri_zen)));

LV = lv*DHI/normalization_factor;

end